--- #YAML:1.0
name:               Garivini
version:            0.001
abstract:           Mostly language agnostic job persistence engine for Gearman
author:
    - Dormando <dormando@rydia.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBI:              0
    Gearman::Client:  0
    Gearman::Worker:  0
    JSON:             0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
